py_binary(
    name = "add_spotlight",
    srcs = [
        "add_spotlight.py",
    ],
    deps = [
        "//py:paths_lib",
        "//py:spotlight_lib",
        "//prototype:article_repo_lib",
    ],
)
