java_binary(
    name = "WordCount",
    srcs = [
        "WordCount.java",
    ],
    main_class = "WordCount",
    deps = [
        "//:org_apache_hadoop_hadoop_common",
        "//:org_apache_hadoop_hadoop_mapreduce_client_core",
    ],
)
