# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sentence.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sentence.proto',
  package='prvak',
  serialized_pb=_b('\n\x0esentence.proto\x12\x05prvak\"n\n\rSentenceToken\x12\n\n\x02id\x18\x06 \x01(\x05\x12\x14\n\x0cstart_offset\x18\x01 \x01(\x05\x12\x12\n\nend_offset\x18\x02 \x01(\x05\x12\r\n\x05lemma\x18\x03 \x01(\t\x12\x0b\n\x03pos\x18\x04 \x01(\t\x12\x0b\n\x03ner\x18\x05 \x01(\t\"S\n\x07Mention\x12\x12\n\nsentenceId\x18\x01 \x01(\x05\x12\x13\n\x0bstartWordId\x18\x02 \x01(\x05\x12\x11\n\tendWordId\x18\x03 \x01(\x05\x12\x0c\n\x04text\x18\x06 \x01(\t\"I\n\x0b\x43oreference\x12 \n\x08mentions\x18\x01 \x03(\x0b\x32\x0e.prvak.Mention\x12\x18\n\x10wikidataEntityId\x18\x02 \x01(\t\"\x80\x01\n\x08\x44ocument\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x18\n\x10\x61rticle_sanename\x18\x04 \x01(\t\x12\"\n\tsentences\x18\x02 \x03(\x0b\x32\x0f.prvak.Sentence\x12(\n\x0c\x63oreferences\x18\x03 \x03(\x0b\x32\x12.prvak.Coreference\"J\n\x08Sentence\x12\n\n\x02id\x18\x03 \x01(\x05\x12\x0c\n\x04text\x18\x01 \x01(\t\x12$\n\x06tokens\x18\x02 \x03(\x0b\x32\x14.prvak.SentenceToken\"_\n\x10SpotlightMention\x12\x14\n\x0cstart_offset\x18\x01 \x01(\x05\x12\x12\n\nend_offset\x18\x02 \x01(\x05\x12\x0b\n\x03uri\x18\x03 \x01(\t\x12\x14\n\x0csurface_form\x18\x04 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SENTENCETOKEN = _descriptor.Descriptor(
  name='SentenceToken',
  full_name='prvak.SentenceToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='prvak.SentenceToken.id', index=0,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_offset', full_name='prvak.SentenceToken.start_offset', index=1,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_offset', full_name='prvak.SentenceToken.end_offset', index=2,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lemma', full_name='prvak.SentenceToken.lemma', index=3,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos', full_name='prvak.SentenceToken.pos', index=4,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ner', full_name='prvak.SentenceToken.ner', index=5,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=135,
)


_MENTION = _descriptor.Descriptor(
  name='Mention',
  full_name='prvak.Mention',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentenceId', full_name='prvak.Mention.sentenceId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='startWordId', full_name='prvak.Mention.startWordId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='endWordId', full_name='prvak.Mention.endWordId', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text', full_name='prvak.Mention.text', index=3,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=220,
)


_COREFERENCE = _descriptor.Descriptor(
  name='Coreference',
  full_name='prvak.Coreference',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mentions', full_name='prvak.Coreference.mentions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wikidataEntityId', full_name='prvak.Coreference.wikidataEntityId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=295,
)


_DOCUMENT = _descriptor.Descriptor(
  name='Document',
  full_name='prvak.Document',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='prvak.Document.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='article_sanename', full_name='prvak.Document.article_sanename', index=1,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sentences', full_name='prvak.Document.sentences', index=2,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coreferences', full_name='prvak.Document.coreferences', index=3,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=298,
  serialized_end=426,
)


_SENTENCE = _descriptor.Descriptor(
  name='Sentence',
  full_name='prvak.Sentence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='prvak.Sentence.id', index=0,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text', full_name='prvak.Sentence.text', index=1,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tokens', full_name='prvak.Sentence.tokens', index=2,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=428,
  serialized_end=502,
)


_SPOTLIGHTMENTION = _descriptor.Descriptor(
  name='SpotlightMention',
  full_name='prvak.SpotlightMention',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_offset', full_name='prvak.SpotlightMention.start_offset', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_offset', full_name='prvak.SpotlightMention.end_offset', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uri', full_name='prvak.SpotlightMention.uri', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='surface_form', full_name='prvak.SpotlightMention.surface_form', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=504,
  serialized_end=599,
)

_COREFERENCE.fields_by_name['mentions'].message_type = _MENTION
_DOCUMENT.fields_by_name['sentences'].message_type = _SENTENCE
_DOCUMENT.fields_by_name['coreferences'].message_type = _COREFERENCE
_SENTENCE.fields_by_name['tokens'].message_type = _SENTENCETOKEN
DESCRIPTOR.message_types_by_name['SentenceToken'] = _SENTENCETOKEN
DESCRIPTOR.message_types_by_name['Mention'] = _MENTION
DESCRIPTOR.message_types_by_name['Coreference'] = _COREFERENCE
DESCRIPTOR.message_types_by_name['Document'] = _DOCUMENT
DESCRIPTOR.message_types_by_name['Sentence'] = _SENTENCE
DESCRIPTOR.message_types_by_name['SpotlightMention'] = _SPOTLIGHTMENTION

SentenceToken = _reflection.GeneratedProtocolMessageType('SentenceToken', (_message.Message,), dict(
  DESCRIPTOR = _SENTENCETOKEN,
  __module__ = 'sentence_pb2'
  # @@protoc_insertion_point(class_scope:prvak.SentenceToken)
  ))
_sym_db.RegisterMessage(SentenceToken)

Mention = _reflection.GeneratedProtocolMessageType('Mention', (_message.Message,), dict(
  DESCRIPTOR = _MENTION,
  __module__ = 'sentence_pb2'
  # @@protoc_insertion_point(class_scope:prvak.Mention)
  ))
_sym_db.RegisterMessage(Mention)

Coreference = _reflection.GeneratedProtocolMessageType('Coreference', (_message.Message,), dict(
  DESCRIPTOR = _COREFERENCE,
  __module__ = 'sentence_pb2'
  # @@protoc_insertion_point(class_scope:prvak.Coreference)
  ))
_sym_db.RegisterMessage(Coreference)

Document = _reflection.GeneratedProtocolMessageType('Document', (_message.Message,), dict(
  DESCRIPTOR = _DOCUMENT,
  __module__ = 'sentence_pb2'
  # @@protoc_insertion_point(class_scope:prvak.Document)
  ))
_sym_db.RegisterMessage(Document)

Sentence = _reflection.GeneratedProtocolMessageType('Sentence', (_message.Message,), dict(
  DESCRIPTOR = _SENTENCE,
  __module__ = 'sentence_pb2'
  # @@protoc_insertion_point(class_scope:prvak.Sentence)
  ))
_sym_db.RegisterMessage(Sentence)

SpotlightMention = _reflection.GeneratedProtocolMessageType('SpotlightMention', (_message.Message,), dict(
  DESCRIPTOR = _SPOTLIGHTMENTION,
  __module__ = 'sentence_pb2'
  # @@protoc_insertion_point(class_scope:prvak.SpotlightMention)
  ))
_sym_db.RegisterMessage(SpotlightMention)


# @@protoc_insertion_point(module_scope)
