STORAGE_NODE=brno3-cerit
STORAGE_ROOT=/storage/$STORAGE_NODE
STORAGE_HOME=$STORAGE_ROOT/home/prvak
WIKI2TEXT_BINARY=$STORAGE_HOME/wiki2text

CORENLP_DIR=$STORAGE_HOME/corenlp
CORENLP_RUNNER_SH=$CORENLP_DIR/stanford-corenlp-full-2015-12-09/corenlp.sh
