import org.json.*;
import org.apache.hadoop.hbase.util.Bytes;
import org.apache.hadoop.hbase.client.Get;
import org.apache.hadoop.hbase.client.Result;

public class SavedDocument {
	public String title;
	public String plaintext;
	public String corenlpXml;
	public JSONObject spotlightJson;

	// Generated by add_join.
	// private TODO sentences;
	// private TODO coreferences;
	// private TODO spotlight_mentions;

	public static Get getGet(String title) {
		Get get = new Get(Bytes.toBytes(title));
		get.addColumn(ArticlesTable.WIKI, ArticlesTable.PLAINTEXT);
		get.addColumn(ArticlesTable.WIKI, ArticlesTable.CORENLP_XML);
		get.addColumn(ArticlesTable.WIKI, ArticlesTable.SPOTLIGHT_JSON);
		return get;
	}

	public SavedDocument(Result result) {
//		if (result.getRow() == null) {
//			throw new InvalidArgumentException("Null rowkey");
//		}

		title = new String(result.getRow());

		byte[] plaintextBytes = result.getValue(ArticlesTable.WIKI, ArticlesTable.PLAINTEXT);
		if (plaintextBytes != null) {
			plaintext = new String(plaintextBytes);
		} else {
			plaintext = null;
		}

		byte[] corenlpXmlBytes = result.getValue(ArticlesTable.WIKI, ArticlesTable.CORENLP_XML);
		if (corenlpXmlBytes != null) {
			corenlpXml = new String(corenlpXmlBytes);
		} else {
			corenlpXml = null;
		}
		byte[] spotlightJsonBytes = result.getValue(ArticlesTable.WIKI, ArticlesTable.SPOTLIGHT_JSON);
		if (spotlightJsonBytes != null) {
			spotlightJson = new JSONObject(new String(spotlightJsonBytes));
		} else {
			spotlightJson = null;
		}
	}

	public JSONObject toJSON() {
		JSONObject json = new JSONObject();
		json.put("title", title);
		json.put("plaintext", plaintext);
		json.put("corenlp_xml", corenlpXml);
		json.put("spotlight_json", spotlightJson);
		return json;
	}
}
