py_binary(
    name = "run_nolock",
    srcs = [
        "run_nolock.py",
    ],
    deps = [
    ],
)

py_binary(
    name = "get_job_machine",
    srcs = [
        "get_job_machine.py",
    ],
    deps = [
        "//prototype/lib:pbs_util_lib",
    ],
)

py_binary(
    name = "kill_all_jobs",
    srcs = [
        "kill_all_jobs.py",
    ],
    deps = [
        "//prototype/lib:pbs_util_lib",
    ],
)

py_binary(
    name = "show_all_jobs",
    srcs = [
        "show_all_jobs.py",
    ],
    deps = [
        "//prototype/lib:pbs_util_lib",
    ],
)
