java_binary(
    name = "make_training_samples",
    srcs = [
        "MakeTrainingSamples.java",
    ],
    main_class = "MakeTrainingSamples",
    deps = [
        "//prototype:ArticleRepository",
        "//:org_json_json",
        "//hadoop:GenerateTrainingSamples",
        "//hadoop:WikidataClient",
    ],
)
